package com.sample.androidsampleprjct.vo;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "LT_LOTTERY".
 */
public class Lottery {

    private Long id;
    /** Not-null value. */
    private String lotteryCode;
    /** Not-null value. */
    private String expect;
    private String candidateCode;
    private String candidateCode2;
    private java.util.Date regDate;
    private String isWin;

    public Lottery() {
    }

    public Lottery(Long id) {
        this.id = id;
    }

    public Lottery(Long id, String lotteryCode, String expect, String candidateCode, String candidateCode2, java.util.Date regDate, String isWin) {
        this.id = id;
        this.lotteryCode = lotteryCode;
        this.expect = expect;
        this.candidateCode = candidateCode;
        this.candidateCode2 = candidateCode2;
        this.regDate = regDate;
        this.isWin = isWin;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getLotteryCode() {
        return lotteryCode;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setLotteryCode(String lotteryCode) {
        this.lotteryCode = lotteryCode;
    }

    /** Not-null value. */
    public String getExpect() {
        return expect;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setExpect(String expect) {
        this.expect = expect;
    }

    public String getCandidateCode() {
        return candidateCode;
    }

    public void setCandidateCode(String candidateCode) {
        this.candidateCode = candidateCode;
    }

    public String getCandidateCode2() {
        return candidateCode2;
    }

    public void setCandidateCode2(String candidateCode2) {
        this.candidateCode2 = candidateCode2;
    }

    public java.util.Date getRegDate() {
        return regDate;
    }

    public void setRegDate(java.util.Date regDate) {
        this.regDate = regDate;
    }

    public String getIsWin() {
        return isWin;
    }

    public void setIsWin(String isWin) {
        this.isWin = isWin;
    }

}
