package com.sample.androidsampleprjct.vo;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "LT_SSQ_REMOTE".
 */
public class SSQExtVO {

    private Long id;
    private String expect;
    private String openCode;
    private String openTime;
    private String openTimeStamp;
    private String flag;
    private java.util.Date regDtm;

    public SSQExtVO() {
    }

    public SSQExtVO(Long id) {
        this.id = id;
    }

    public SSQExtVO(Long id, String expect, String openCode, String openTime, String openTimeStamp, String flag, java.util.Date regDtm) {
        this.id = id;
        this.expect = expect;
        this.openCode = openCode;
        this.openTime = openTime;
        this.openTimeStamp = openTimeStamp;
        this.flag = flag;
        this.regDtm = regDtm;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getExpect() {
        return expect;
    }

    public void setExpect(String expect) {
        this.expect = expect;
    }

    public String getOpenCode() {
        return openCode;
    }

    public void setOpenCode(String openCode) {
        this.openCode = openCode;
    }

    public String getOpenTime() {
        return openTime;
    }

    public void setOpenTime(String openTime) {
        this.openTime = openTime;
    }

    public String getOpenTimeStamp() {
        return openTimeStamp;
    }

    public void setOpenTimeStamp(String openTimeStamp) {
        this.openTimeStamp = openTimeStamp;
    }

    public String getFlag() {
        return flag;
    }

    public void setFlag(String flag) {
        this.flag = flag;
    }

    public java.util.Date getRegDtm() {
        return regDtm;
    }

    public void setRegDtm(java.util.Date regDtm) {
        this.regDtm = regDtm;
    }

}
