package com.sample.androidsampleprjct.util.db;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.sample.androidsampleprjct.dao.lottery.LotteryDao;
import com.sample.androidsampleprjct.vo.Lottery;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig lotteryDaoConfig;

    private final LotteryDao lotteryDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        lotteryDaoConfig = daoConfigMap.get(LotteryDao.class).clone();
        lotteryDaoConfig.initIdentityScope(type);

        lotteryDao = new LotteryDao(lotteryDaoConfig, this);

        registerDao(Lottery.class, lotteryDao);
    }
    
    public void clear() {
        lotteryDaoConfig.getIdentityScope().clear();
    }

    public LotteryDao getLotteryDao() {
        return lotteryDao;
    }

}
