package com.sample.androidsampleprjct.util.db;

import android.database.sqlite.SQLiteDatabase;

import com.sample.androidsampleprjct.dao.lottery.LotteryDao;
import com.sample.androidsampleprjct.dao.lottery.SSQDao;
import com.sample.androidsampleprjct.dao.lottery.SSQExtVODao;
import com.sample.androidsampleprjct.vo.Lottery;
import com.sample.androidsampleprjct.vo.SSQ;
import com.sample.androidsampleprjct.vo.SSQExtVO;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig lotteryDaoConfig;
    private final DaoConfig sSQDaoConfig;
    private final DaoConfig sSQExtVODaoConfig;

    private final LotteryDao lotteryDao;
    private final SSQDao sSQDao;
    private final SSQExtVODao sSQExtVODao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        lotteryDaoConfig = daoConfigMap.get(LotteryDao.class).clone();
        lotteryDaoConfig.initIdentityScope(type);

        sSQDaoConfig = daoConfigMap.get(SSQDao.class).clone();
        sSQDaoConfig.initIdentityScope(type);

        sSQExtVODaoConfig = daoConfigMap.get(SSQExtVODao.class).clone();
        sSQExtVODaoConfig.initIdentityScope(type);

        lotteryDao = new LotteryDao(lotteryDaoConfig, this);
        sSQDao = new SSQDao(sSQDaoConfig, this);
        sSQExtVODao = new SSQExtVODao(sSQExtVODaoConfig, this);

        registerDao(Lottery.class, lotteryDao);
        registerDao(SSQ.class, sSQDao);
        registerDao(SSQExtVO.class, sSQExtVODao);
    }
    
    public void clear() {
        lotteryDaoConfig.getIdentityScope().clear();
        sSQDaoConfig.getIdentityScope().clear();
        sSQExtVODaoConfig.getIdentityScope().clear();
    }

    public LotteryDao getLotteryDao() {
        return lotteryDao;
    }

    public SSQDao getSSQDao() {
        return sSQDao;
    }

    public SSQExtVODao getSSQExtVODao() {
        return sSQExtVODao;
    }

}
